- name: Logging Setup für Windows EC2
  hosts: winhosts
  gather_facts: yes
  tasks:

    - name: Prüfe, ob Edge auf Bare-metal läuft
      win_shell: |
        $proc = Get-Process -Name "msedge" -ErrorAction SilentlyContinue
        if ($proc) { Write-Output "baremetal" } else { Write-Output "none" }
      register: edge_status

    - name: Prüfe, ob Edge in Container läuft (Docker)
      win_shell: |
        $docker = Get-Command docker -ErrorAction SilentlyContinue
        if ($docker) {
          $container = docker ps --filter "name=edge" --format "{{.Names}}"
          if ($container) { Write-Output "container" } else { Write-Output "none" }
        } else {
          Write-Output "none"
        }
      register: edge_container_status

    - name: Setze Variable software_location
      set_fact:
        edge_location: >-
          {% if edge_status.stdout == "baremetal" %}
            baremetal
          {% elif edge_container_status.stdout == "container" %}
            container
          {% else %}
            not_installed
          {% endif %}

    - name: Erstelle Logging-Verzeichnis
      win_file:
        path: C:\myapp
        state: directory

    - name: Logging konfigurieren für Edge
      win_shell: |
        "Software: Microsoft Edge
        Location: {{ edge_location }}" | Out-File -FilePath C:\myapp\logging_edge.txt -Encoding UTF8

    - name: Lade Logfile zu S3
      win_shell: |
        Import-Module AWSPowerShell
        Write-S3Object -BucketName "ansible3testnow" -File "C:\myapp\logging_edge.txt" -Key "logging_edge.txt" -Region "eu-central-1"
